### PR TITLE
Add run-time options for dry pressure and moisture-corrected mass fluxes in advection

### LINKED ISSUE #316: [BUG/ISSUE] Using total pressure in advection leaves moisture imprint
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Confirm you have reviewed the following documentation

- [X] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [X] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [X] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [X] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

The GCHP 14.0.0 transport tracer benchmark shows bias in the passive tracer concentrations, with reduced concentrations in areas with greater moisture. See [here](http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/14.0.0-rc.3/GCHP/TransportTracers/BenchmarkResults/GCHP_version_comparison/PassiveTracers/AnnualMean/PassiveTracers_Surface_AnnualMean.pdf) for the passive tracer annual surface concentrations of 14.0.0 compared to 13.2.0, also shown below. 
Correct passive tracer concentrations in that simulation are uniform, as shown in the 13.2.0 plot in the upper left. The bias in 14.0.0 indicates something is wrong in the model. See [here](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_14.0.0#1-year_transport_GCHP_version_comparison_.2814.0.0_vs_13.2.0.29) for all artifacts generated during that benchmark.

Screen Shot 2023-05-19 at 4 05 03 PM

I looked into the source of the change and traced it to submodule updates submitted in https://github.com/geoschem/GCHP/issues/189 and the accompanying PR https://github.com/geoschem/GCHP/pull/181. The bias source is specifically the change from using dry pressure to total pressure. An unrelated issue came in with that update which did not cause the moisture bias. See https://github.com/geoschem/GCHP/issues/315 for more on that issue.

### PR DESCRIPTION
**Pull request by lizziel**
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Confirm you have reviewed the following documentation

- [X] [Contributing guidelines](https://gchp.readthedocs.io/en/latest/reference/CONTRIBUTING.html)

### Describe the update

This PR addresses the issue described in https://github.com/geoschem/GCHP/issues/316. It includes the following changes:
1. Add back connectivities for dry pressure for use in advection. These had been deleted in 13.4 to use total pressure.
2. Add `GCHPctmEnv` imports PS2 and SPHU2 (from read from GMAO data).
3. Add `GCHPctmEnv` exports DryPLE0 and DryPLE1 (to pass to advection).
4. Clean up `GCHPctmEnv_GridCompMod` by adding standard GEOS-Chem documentation headers and descriptions
5. Add dry pressure as an option to use in advection by bringing back code to compute dry pressure and adding a run-time switch in config file `GCHP.rc` to toggle it on and off.
6. Add option to convert mass flux imports to dry mass fluxes by correcting by moisture. This is toggled by another new run-time switch in config file `GCHP.rc`.

### Expected changes

These updates, together with submodule updates in the following PRs, should correct the moisture bias we see in the 14.0.0 transport tracer benchmark (see [here](http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/14.0.0-rc.3/GCHP/TransportTracers/BenchmarkResults/GCHP_version_comparison/PassiveTracers/AnnualMean/PassiveTracers_Surface_AnnualMean.pdf) for an example).

### Related Github Issue(s)

* https://github.com/geoschem/GCHP/issues/316

### Accompanying submodule pull requests

* https://github.com/geoschem/geos-chem/pull/1797
* https://github.com/geoschem/FVdycoreCubed_GridComp/pull/7

### CODE REVIEW

**Comment by lizziel** [comment]
@msulprizio, hold off on merging this until you get the go-ahead from me. I need to resolved conflicts in https://github.com/geoschem/geos-chem/pull/1797 introduced because of the pressure fixes in the same file. This PR also has those fixes but I reformatted some of the code.

**Comment by msulprizio** [comment]
@lizziel OK, I will hold off on merging.

**Review by msulprizio — CHANGES_REQUESTED** [review]
@lizziel These changes look good, but CHANGELOG.md should be updated before merging.

**Comment by lizziel** [comment]
This passed GCHP integration tests and is now ready for merge.

**Review by msulprizio — APPROVED** [review]

**Pull request merged**
