### PR TITLE
Replace stalebot with "stale" GitHub action

### PR DESCRIPTION
**Pull request by yantosca**
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://gchp.readthedocs.io/en/latest/reference/CONTRIBUTING.html)

### Describe the update

This PR does the following:
1. Updates the list of labels for issues/PRs that should not be marked as "stale"
2. Retires "stalebot" and corresponding config files
3. Uses the GitHub Action "stale" to mark issues as stale, and adds corresponding config file

### Expected changes
This is a zero-diff update that only affects when GitHub issues are marked as "stale".

### Related Github Issue(s)
- https://github.com/geoschem/GCClassic/pull/56
- https://github.com/geoschem/HEMCO/pull/274
- https://github.com/geoschem/geos-chem/pull/2260
- https://github.com/geoschem/gcpy/pull/315

### CODE REVIEW

**Review by msulprizio — APPROVED** [review]

**Review by msulprizio — CHANGES_REQUESTED** [review]
Should the base branch here be `dev/14.4.0`? 

Also, this includes committing the submodule updates for GEOS-Chem (but not HEMCO) which we don't typically do in the super project PRs.

**Comment by yantosca** [comment]
@msulprizio, yes, I could make a submodule update instructions list and we'd have to merge them in separately (maybe after this PR is merged).

**Comment by yantosca** [comment]
@msulprizio: The base branch is now dev/14.4.0.

**Review by msulprizio — APPROVED** [review]
Now approved

**Pull request merged**
