### PR TITLE
Use separate_arguments() on VECT options

### PR DESCRIPTION
**Pull request by LiamBindle**
Enables shell-like quoting of compiler options for CMAKE_BUILD_TYPE=Release.

Currently setting `CMAKE_BUILD_TYPE=Release` will cause the build to fail. Note that the default is `CMAKE_BUILD_TYPE=RelWithDebInfo`. This PR implements support for shell-like quoting (`SHELL:` pattern) in compiler options for `Release` configuration. It looks like these flags include some platform specific assumptions, so the compiled executable still might not run.

This isn't a priority, but it's something that should be fixed.

### CODE REVIEW

**Comment by lizziel** [comment]
Is this still going into 13.1?

**Comment by msulprizio** [comment]
I have no problems including this in 13.1.0 still if @LiamBindle recommends it. 

@lizziel could you review the changes before we merge in?

**Comment by LiamBindle** [comment]
I think this is safe to go into 13.1

**Comment by lizziel** [comment]
It looks like this update is all in the submodules. We're trying to not do super-project merges that contain submodule changes since sometimes the submodules in the PR have diverged from dev. Changing the PR hash can make the submodules go to a different branch. Also, there's a conflict in ESMA_cmake.

**Comment by lizziel** [comment]
I updated the target from main to dev and now all changed submodule files have conflicts. I think the changes were on top of an earlier version prior to the GMAO library updates. @LiamBindle, could you rebase and test with latest dev?

**Comment by LiamBindle** [comment]
Right, it looks like it's outdated. 

This is a mostly coesmetic fix (since RelWithDebInfor==Release for us) so I don't think it should in any way hold up 13.1. I doubt I'll have time to get to this before 13.1. In the build system update that I'm going to do soon, I'll include this.

**Comment by lizziel** [comment]
Thanks @LiamBindle!

**Pull request closed without merging**
